---
- name: Deploy Node.js App to Kubernetes
  hosts: localhost
  gather_facts: false
  vars:
    image_tag: "{{ BUILD_NUMBER }}"
    docker_image: "webapp"


  tasks:
    - name: Copy Kubernetes YAML files
      copy:
        src: "{{ item }}"
        dest: "/tmp/k8s/"
      with_fileglob:
        - "webapp/*.yaml"

    - name: Find YAML files for substitution
      find:
        paths: "/tmp/k8s/"
        patterns: "*.yaml"
      register: yaml_files

    - name: Substitute image tag in Kubernetes YAML files
      replace:
        path: "{{ item.path }}"
        regexp: "(webapp):.*$"
        replace: "\\1:{{ image_tag }}"
      loop: "{{ yaml_files.files }}"

    - name: Apply Kubernetes YAML files
      command: kubectl apply -f "{{ item.path }}"
      loop: "{{ yaml_files.files }}"
