pipeline {
  agent any
  
  environment {
    //API_KEY = credentials('AIzaSyCufNpGA1BRPkBWt0VWmMwVvoEbkaSdvYA')
    //DATABASE_URL = credentials('35.246.177.84')
    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }
  
  stages {

    stage('Checkout') {
      steps {
        // Cloning the repository into the workspace
        git branch: 'main', url: 'https://github.com/Ryuuramaru/webapp.git'
      }
    }

    stage('Build') {
      steps {
        
        // Install dependencies and build the web app
        dir('webapp') {
          sh 'npm install'
          sh 'npm run build'
          }
        }
        
        // Optionally, you can run tests here
        //sh 'npm test'
      }
    }
    
    stage('Containerize') {
      steps {
        // Build the Docker image for the web app
        sh "docker build -t webapp:${IMAGE_TAG} ."
      }
    }

    stage('Push to Registry') {
      steps {
        // Push the Docker image to the registry
        sh 'docker tag webapp:${IMAGE_TAG} gcr.io/metal-filament-395208/webapp:${IMAGE_TAG}'
        sh 'docker push gcr.io/metal-filament-395208/webapp:${IMAGE_TAG}'
      }
    }

    stage('Deploy') {
      steps {
        // Deploy the Docker image to the Kubernetes cluster
        sh 'kubectl apply -f webapp/deployment.yaml'
      }
    }  
  }
  
  post {
    /*always {
      // Clean up the Docker image after the deployment
      script {
        //docker.image(env.DOCKER_IMAGE_TAG).remove() 
        //bugged at the moment
      }
    }*/
    success {
      // Optionally, notify on success
      // You can use Slack, email, or any other notification method.
      echo 'Deployment successful! Notify your team.'
    }
    failure {
      // Optionally, notify on failure
      // You can use Slack, email, or any other notification method.
      echo 'Deployment failed! Notify your team.'
    }
  }
}
