apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible-container
          image: gcr.io/metal-filament-395208/ansible:latest
