apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: gcr.io/metal-filament-395208/webapp:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
          # Add other container settings as needed